version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=superpet
      - TZ=America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/superpet?sslmode=disable
      - TZ=America/Sao_Paulo
      - SUPERPET_DELIVERY_URL=http://gotenberg
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/startdev.sh"]
    command: ["sh", "-c", "cd /app/app && make devserver"]
    restart: always
    volumes:
      - ./media:/app/app/media
      - ./api:/app/app/api
      - ./util:/app/app/util
      - ./db:/app/app/db
  gotenberg:
    container_name: pdf-generator
    image: gotenberg/gotenberg:7
  front:
    container_name: front
    build:
      context: .
      dockerfile: front/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
      - NEXT_PUBLIC_SUPERPET_DELIVERY_URL=http://localhost
    restart: always
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
volumes:
  postgres_data:
