FROM golang:1.21.0-alpine3.18 AS builder
WORKDIR /app
COPY . .
RUN go build -o main main.go
RUN apk add curl
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
RUN apk add make

FROM golang:1.21.0-alpine3.18
ENV SUPERPET_DELIVERY_URL=http://gotenberg
WORKDIR /app
RUN apk add make
RUN go install github.com/codegangsta/gin@latest
COPY --from=builder . .
COPY --from=builder /app/migrate.linux-amd64 ./migrate
COPY app.env .
COPY startdev.sh .
COPY wait-for.sh .
COPY db/migration ./migration
RUN chmod +x ./startdev.sh
RUN chmod +x ./wait-for.sh

EXPOSE 8080
CMD [ "/app/app/main" ]
ENTRYPOINT [ "/app/startdev.sh" ]
